### PR TITLE
Update Sharp to latest version

### PR DESCRIPTION
**Pull request by jalamprea**
With the latest version of Sharp, there are some bugs fixed and some debug messages removed

### CODE REVIEW

**Comment by axe312ger** [comment]
And most important: It adds support for prebuilt binaries to speed up installation :)

http://sharp.pixelplumbing.com/en/stable/changelog/#v0200-5th-march-2018

**Comment by axe312ger** [comment]
@zouhir having the old sharp version results in a native library collision when using lqip together with other modules already updated to sharp 0.20

This very simple PR would fix it. Please merge and release 🚀 

```
module.js:689
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen(.../node_modules/sharp/build/Release/sharp.node, 1): Library not loaded: @rpath/libvips-cpp.42.dylib
  Referenced from: .../node_modules/sharp/build/Release/sharp.node
  Reason: Incompatible library version: sharp.node requires version 51.0.0 or later, but libvips-cpp.42.dylib provides version 50.0.0
```

**Comment by zouhir** [comment]
Will merge and release in upcoming few hours! Nice update, thanks!

**Comment by josenobile** [comment]
Hi @zouhir , venus hours? :-) Can you please accept the pull request.

**Pull request merged**
